CREATE USER 'IT '@' %'
IDENTIFIED BY 'TESTIT';
GRANT ALL PRIVILEGES ON waterbuddy2.* TO 'IT' WITH GRANT OPTION;

CREATE USER 'SenM  '@' %'
IDENTIFIED BY 'TESTSENM';
GRANT ALL PRIVILEGES ON waterbuddy2.artikelen TO 'SenM' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON waterbuddy2.bestellingen TO 'SenM' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON waterbuddy2.klanten TO 'SenM' WITH GRANT OPTION;
GRANT ALL PRIVILIGES ON waterbuddy2.bestellingdetails TO 'SenM' WITH GRANT OPTION;

CREATE USER 'HR  '@' %'
IDENTIFIED BY 'TESTHR';
GRANT ALL PRIVILEGES ON waterbuddy2.werknemers TO 'HR' WITH GRANT OPTION;

CREATE USER 'FIN  '@' %'
IDENTIFIED BY 'TESTFIN';
GRANT ALL PRIVILEGES ON waterbuddy2.artikelen TO 'FIN' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON waterbuddy2.bestellingen TO 'FIN' WITH GRANT OPTION;
GRANT ALL PRIVILIGES ON waterbuddy2.bestellingdetails TO 'FIN' WITH GRANT OPTION;

